(* This file is generated by Why3's Coq driver *)
(* Beware! Only edit allowed sections below    *)
Require Import BuiltIn.
Require BuiltIn.

Parameter a: Prop.

Parameter b: Prop.

(* Why3 goal *)
Theorem Thm00 : (a /\ b) -> b /\ a.
(* Why3 intros (h1,h2). *)
Proof.
intros (h1,h2).

Qed.

